In [1]:
import pandas as pd

In [5]:
filename = 'H2_HOFF_PUNIF_251016_130958.csv'

data = pd.read_csv(filename, header = 6)

In [8]:
data.head()

,[run number],p-visaaccs,probability-signals,p-app,same-policy-test?,herd-T,allow-return?,two-networks?,diaspora-2,p-success-all,...,r7.3-list,real-utility-1-list,real-utility-2-list,D-1-list,D_0-list,num-1_L1,num-1_L2,num_0_L1,num_0_L2,my-seed
0,5,1,1,0.01,True,10000,True,True,0.163,0.0,...,[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0],[0.01 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...,[0.01 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...,"[""NA"" ""NA"" ""NA"" ""NA"" ""NA"" ""NA"" ""NA"" ""NA"" ""NA"" ...","[""NA"" ""NA"" ""NA"" ""NA"" ""NA"" ""NA"" ""NA"" ""NA"" ""NA"" ...",[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0],[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0],[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0],[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0],1472236146
1,3,1,1,0.01,True,10000,True,True,0.163,0.0,...,[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0],[0.01 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...,[0.01 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...,"[""NA"" ""NA"" ""NA"" ""NA"" ""NA"" ""NA"" ""NA"" ""NA"" ""NA"" ...","[""NA"" ""NA"" ""NA"" ""NA"" ""NA"" ""NA"" ""NA"" ""NA"" ""NA"" ...",[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0],[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0],[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0],[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0],744785594
2,11,1,1,0.01,True,10000,True,True,0.163,0.0,...,[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0],[0.01 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...,[0.01 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...,"[""NA"" ""NA"" ""NA"" ""NA"" ""NA"" ""NA"" ""NA"" ""NA"" ""NA"" ...","[""NA"" ""NA"" ""NA"" ""NA"" ""NA"" ""NA"" ""NA"" ""NA"" ""NA"" ...",[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0],[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0],[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0],[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0],631776052
3,1,1,1,0.01,True,10000,True,True,0.163,0.0,...,[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0],[0.01 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...,[0.01 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...,"[""NA"" ""NA"" ""NA"" ""NA"" ""NA"" ""NA"" ""NA"" ""NA"" ""NA"" ...","[""NA"" ""NA"" ""NA"" ""NA"" ""NA"" ""NA"" ""NA"" ""NA"" ""NA"" ...",[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0],[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0],[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0],[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0],1038146984
4,8,1,1,0.01,True,10000,True,True,0.163,0.0,...,[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0],[0.01 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...,[0.01 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...,"[""NA"" ""NA"" ""NA"" ""NA"" ""NA"" ""NA"" ""NA"" ""NA"" ""NA"" ...","[""NA"" ""NA"" ""NA"" ""NA"" ""NA"" ""NA"" ""NA"" ""NA"" ""NA"" ...",[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0],[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0],[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0],[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0],-348521698