In [3]:
import re
import pandas as pd

In [4]:
filename = 'H2_HOFF_PUNIF_251016_130958.csv'

data = pd.read_csv(filename, header = 6)

In [17]:
regex = re.compile(r'^.*(\-list|L(1|2))$')
columns_to_split = filter(regex.match, list(data.columns.values))

In [23]:
num_values = 24
for c in columns_to_split:
    split_values = data[c].str.split(' ', num_values, expand = True)
    for i in range(1, len(split_values.columns)):
        data[c + '-' + str(i)] = split_values[i]

In [25]:
data.head()

,[run number],p-visaaccs,probability-signals,p-app,same-policy-test?,herd-T,allow-return?,two-networks?,diaspora-2,p-success-all,...,num_0_L2-14,num_0_L2-15,num_0_L2-16,num_0_L2-17,num_0_L2-18,num_0_L2-19,num_0_L2-20,num_0_L2-21,num_0_L2-22,num_0_L2-23
0,5,1,1,0.01,True,10000,True,True,0.163,0.0,...,0,0,0,0,0,0,0,0,0,0]
1,3,1,1,0.01,True,10000,True,True,0.163,0.0,...,0,0,0,0,0,0,0,0,0,0]
2,11,1,1,0.01,True,10000,True,True,0.163,0.0,...,0,0,0,0,0,0,0,0,0,0]
3,1,1,1,0.01,True,10000,True,True,0.163,0.0,...,0,0,0,0,0,0,0,0,0,0]
4,8,1,1,0.01,True,10000,True,True,0.163,0.0,...,0,0,0,0,0,0,0,0,0,0]